include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    always_declare_return_types: true
    unnecessary_this: true
    use_build_context_synchronously: false