#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

regex='^(revert: )?(feat|fix|style|refactor|perf|test|workflow|ci|chore|types|wip|docs)(\([^)]+\))?: .{1,72}$'

if echo "$commit_msg" | grep -Eq "$regex"; then
  exit 0
else
  echo "Commit message does not match the Conventional Commit format."
  echo ""
  echo "Expected format:"
  echo "<type>(<scope>): <subject>"
  echo "Example: feat(home): add new widget"
  exit 1
fi
