name: Flutter Lint & Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - run: flutter pub get

      - name: Validate formatting
        run: dart format . --output=none --set-exit-if-changed

  analyze:
    name: Dart Lint Analysis
    runs-on: ubuntu-latest
    needs: check-format

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze --fatal-warnings
